version: '3.7'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.1'
    container_name: elasticsearch
    volumes:
      - 'data_es:/usr/share/elasticsearch/data'
    environment:
      - discovery.type=single-node
    ports:
      - '9300:9200'
    networks:
      - esnet
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.10.1'
    container_name: kibina
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    volumes:
      - './kibana.yml:/usr/share/kibana/config/kibana.yml'
    ports:
      - '5701:5601'
    networks:
      - esnet
volumes:
  data_es:
    driver: local
networks:
  esnet: null